#!/bin/sh /etc/rc.common

START=99
STOP=15

boot() {
	/usr/share/passwall/app.sh boot
}

start() {
	/usr/share/passwall/app.sh start
	uci set shadowsocksr.@global[0].pdnsd_enable='0'
	uci del shadowsocksr.@global[0].tunnel_forward
	uci commit shadowsocksr
	uci set passwall.@global[0].dns_mode='nonuse'
	uci del passwall.@global[0].up_trust_pdnsd_dns
	uci del passwall.@global[0].dns_forward
	uci commit passwall
}

stop() {
	/usr/share/passwall/app.sh stop
}

restart() {
	stop
	start
}
